export const FIRST_NAMES = [
  'Liam','Noah','Lucas','Mateo','Leo','Hugo','Louis','Jules','Adam','Sofia',
  'Marco','Diego','Carlos','Pablo','Sergio','Andrés','Joaquín','Iván','Rafa','Bruno',
  'Kai','Erik','Lars','Jonas','Felix','Maximilian','Jan','Tobias','Anton','Niko',
  'Pierre','Antoine','Théo','Mathis','Romain','Quentin','Enzo','Yanis','Nathan','Tom',
  'Mohamed','Yusuf','Omar','Hassan','Karim','Riad','Ismael','Adil','Zayd','Tariq',
  'Kenji','Hiro','Sho','Daiki','Ren','Min-jun','Ji-ho','Sung','Tao','Wei',
  'Kwame','Kofi','Sadio','Jamal','Aaron','Marcus','Jordan','Tyler','Ethan','Dylan'
];
export const LAST_NAMES = [
  'Silva','García','Martínez','Rodríguez','Hernández','López','Pérez','Sánchez','Ramírez','Torres',
  'Müller','Schmidt','Schneider','Fischer','Weber','Wagner','Becker','Hoffmann','Schäfer','Koch',
  'Dubois','Laurent','Martin','Bernard','Petit','Moreau','Lefebvre','Rousseau','Fontaine','Girard',
  'Rossi','Russo','Ferrari','Esposito','Bianchi','Romano','Colombo','Ricci','Marino','Greco',
  'Smith','Jones','Williams','Brown','Taylor','Wilson','Davies','Evans','Walker','Wright',
  'Diallo','Touré','Koné','Mensah','Owusu','Adeyemi','Okafor','Mbappé','Sané','Nkunku',
  'Tanaka','Suzuki','Sato','Watanabe','Ito','Kim','Park','Lee','Wang','Chen'
];
export const NATIONS = [
  '🇪🇸 ESP','🇩🇪 GER','🇫🇷 FRA','🇮🇹 ITA','🇬🇧 ENG','🇧🇷 BRA','🇦🇷 ARG','🇵🇹 POR',
  '🇳🇱 NED','🇧🇪 BEL','🇲🇽 MEX','🇺🇸 USA','🇯🇵 JPN','🇰🇷 KOR','🇲🇦 MAR','🇨🇮 CIV',
  '🇸🇳 SEN','🇳🇬 NGA','🇨🇴 COL','🇺🇾 URU','🇨🇭 SUI','🇦🇹 AUT','🇩🇰 DEN','🇸🇪 SWE',
];

export const NATIONS_MAP: Record<string, { name: string; code2: string; emoji: string }> = {
  'ESP': { name: 'Spain', code2: 'es', emoji: '🇪🇸' },
  'GER': { name: 'Germany', code2: 'de', emoji: '🇩🇪' },
  'FRA': { name: 'France', code2: 'fr', emoji: '🇫🇷' },
  'ITA': { name: 'Italy', code2: 'it', emoji: '🇮🇹' },
  'ENG': { name: 'England', code2: 'gb-eng', emoji: '🇬🇧' },
  'SCO': { name: 'Scotland', code2: 'gb-sct', emoji: '🏴󠁧󠁢󠁳󠁣󠁴󠁿' },
  'WAL': { name: 'Wales', code2: 'gb-wls', emoji: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  'NIR': { name: 'Northern Ireland', code2: 'gb-nir', emoji: '🏴' },
  'IRL': { name: 'Ireland', code2: 'ie', emoji: '🇮🇪' },
  'BRA': { name: 'Brazil', code2: 'br', emoji: '🇧🇷' },
  'ARG': { name: 'Argentina', code2: 'ar', emoji: '🇦🇷' },
  'POR': { name: 'Portugal', code2: 'pt', emoji: '🇵🇹' },
  'NED': { name: 'Netherlands', code2: 'nl', emoji: '🇳🇱' },
  'BEL': { name: 'Belgium', code2: 'be', emoji: '🇧🇪' },
  'MEX': { name: 'Mexico', code2: 'mx', emoji: '🇲🇽' },
  'USA': { name: 'United States', code2: 'us', emoji: '🇺🇸' },
  'JPN': { name: 'Japan', code2: 'jp', emoji: '🇯🇵' },
  'KOR': { name: 'South Korea', code2: 'kr', emoji: '🇰🇷' },
  'MAR': { name: 'Morocco', code2: 'ma', emoji: '🇲🇦' },
  'CIV': { name: 'Ivory Coast', code2: 'ci', emoji: '🇨🇮' },
  'SEN': { name: 'Senegal', code2: 'sn', emoji: '🇸🇳' },
  'NGA': { name: 'Nigeria', code2: 'ng', emoji: '🇳🇬' },
  'COL': { name: 'Colombia', code2: 'co', emoji: '🇨🇴' },
  'URU': { name: 'Uruguay', code2: 'uy', emoji: '🇺🇾' },
  'SUI': { name: 'Switzerland', code2: 'ch', emoji: '🇨🇭' },
  'AUT': { name: 'Austria', code2: 'at', emoji: '🇦🇹' },
  'DEN': { name: 'Denmark', code2: 'dk', emoji: '🇩🇰' },
  'SWE': { name: 'Sweden', code2: 'se', emoji: '🇸🇪' },
  'CRO': { name: 'Croatia', code2: 'hr', emoji: '🇭🇷' },
  'UKR': { name: 'Ukraine', code2: 'ua', emoji: '🇺🇦' },
  'POL': { name: 'Poland', code2: 'pl', emoji: '🇵🇱' },
  'TUR': { name: 'Turkey', code2: 'tr', emoji: '🇹🇷' },
  'GRE': { name: 'Greece', code2: 'gr', emoji: '🇬🇷' },
  'EGY': { name: 'Egypt', code2: 'eg', emoji: '🇪🇬' },
  'ALG': { name: 'Algeria', code2: 'dz', emoji: '🇩🇿' },
  'GHA': { name: 'Ghana', code2: 'gh', emoji: '🇬🇭' },
  'CMR': { name: 'Cameroon', code2: 'cm', emoji: '🇨🇲' },
  'CHI': { name: 'Chile', code2: 'cl', emoji: '🇨🇱' },
  'PER': { name: 'Peru', code2: 'pe', emoji: '🇵🇪' },
  'ECU': { name: 'Ecuador', code2: 'ec', emoji: '🇪🇨' },
  'CAN': { name: 'Canada', code2: 'ca', emoji: '🇨🇦' },
  'AUS': { name: 'Australia', code2: 'au', emoji: '🇦🇺' },
  'NZL': { name: 'New Zealand', code2: 'nz', emoji: '🇳🇿' },
  'CHN': { name: 'China', code2: 'cn', emoji: '🇨🇳' },
  'IND': { name: 'India', code2: 'in', emoji: '🇮🇳' },
  'SAU': { name: 'Saudi Arabia', code2: 'sa', emoji: '🇸🇦' },
  'UAE': { name: 'United Arab Emirates', code2: 'ae', emoji: '🇦🇪' },
  'QAT': { name: 'Qatar', code2: 'qa', emoji: '🇶🇦' },
  'IRN': { name: 'Iran', code2: 'ir', emoji: '🇮🇷' },
  'IRQ': { name: 'Iraq', code2: 'iq', emoji: '🇮🇶' },
  'RSA': { name: 'South Africa', code2: 'za', emoji: '🇿🇦' },
  'NOR': { name: 'Norway', code2: 'no', emoji: '🇳🇴' },
  'FIN': { name: 'Finland', code2: 'fi', emoji: '🇫🇮' },
  'ISL': { name: 'Iceland', code2: 'is', emoji: '🇮🇸' },
  'ROU': { name: 'Romania', code2: 'ro', emoji: '🇷🇴' },
  'BUL': { name: 'Bulgaria', code2: 'bg', emoji: '🇧🇬' },
  'HUN': { name: 'Hungary', code2: 'hu', emoji: '🇭🇺' },
  'SRB': { name: 'Serbia', code2: 'rs', emoji: '🇷🇸' },
  'CZE': { name: 'Czech Republic', code2: 'cz', emoji: '🇨🇿' },
  'SVK': { name: 'Slovakia', code2: 'sk', emoji: '🇸🇰' },
  'SLO': { name: 'Slovenia', code2: 'si', emoji: '🇸🇮' },
  'ALB': { name: 'Albania', code2: 'al', emoji: '🇦🇱' },
  'GEO': { name: 'Georgia', code2: 'ge', emoji: '🇬🇪' },
  'RUS': { name: 'Russia', code2: 'ru', emoji: '🇷🇺' },
  'VEN': { name: 'Venezuela', code2: 've', emoji: '🇻🇪' },
  'PAR': { name: 'Paraguay', code2: 'py', emoji: '🇵🇾' },
  'BOL': { name: 'Bolivia', code2: 'bo', emoji: '🇧🇴' },
  'CRC': { name: 'Costa Rica', code2: 'cr', emoji: '🇨🇷' },
  'JAM': { name: 'Jamaica', code2: 'jm', emoji: '🇯🇲' },
  'HON': { name: 'Honduras', code2: 'hn', emoji: '🇭🇳' },
  'PAN': { name: 'Panama', code2: 'pa', emoji: '🇵🇦' },
  'TUN': { name: 'Tunisia', code2: 'tn', emoji: '🇹🇳' },
  'MLI': { name: 'Mali', code2: 'ml', emoji: '🇲🇱' },
  'GUI': { name: 'Guinea', code2: 'gn', emoji: '🇬🇳' },
  'ZAM': { name: 'Zambia', code2: 'zm', emoji: '🇿🇲' },
  'ANG': { name: 'Angola', code2: 'ao', emoji: '🇦🇴' },
  'UZB': { name: 'Uzbekistan', code2: 'uz', emoji: '🇺🇿' },
  'SYR': { name: 'Syria', code2: 'sy', emoji: '🇸🇾' },
  'OMN': { name: 'Oman', code2: 'om', emoji: '🇴🇲' },
  'JOR': { name: 'Jordan', code2: 'jo', emoji: '🇯🇴' },
  'BHR': { name: 'Bahrain', code2: 'bh', emoji: '🇧🇭' },
  'VIE': { name: 'Vietnam', code2: 'vn', emoji: '🇻🇳' },
  'THA': { name: 'Thailand', code2: 'th', emoji: '🇹🇭' },
  'MAS': { name: 'Malaysia', code2: 'my', emoji: '🇲🇾' },
  'INA': { name: 'Indonesia', code2: 'id', emoji: '🇮🇩' },
  'SGP': { name: 'Singapore', code2: 'sg', emoji: '🇸🇬' },
  'PHI': { name: 'Philippines', code2: 'ph', emoji: '🇵🇭' },
  'PAK': { name: 'Pakistan', code2: 'pk', emoji: '🇵🇰' },
  'BAN': { name: 'Bangladesh', code2: 'bd', emoji: '🇧🇩' },
  'SRI': { name: 'Sri Lanka', code2: 'lk', emoji: '🇱🇰' },
  'NEP': { name: 'Nepal', code2: 'np', emoji: '🇳🇵' },
  'LBN': { name: 'Lebanon', code2: 'lb', emoji: '🇱🇧' },
  'PLE': { name: 'Palestine', code2: 'ps', emoji: '🇵🇸' },
  'CYP': { name: 'Cyprus', code2: 'cy', emoji: '🇨🇾' },
  'ISR': { name: 'Israel', code2: 'il', emoji: '🇮🇱' },
  'ARM': { name: 'Armenia', code2: 'am', emoji: '🇦🇲' },
  'AZE': { name: 'Azerbaijan', code2: 'az', emoji: '🇦🇿' },
  'KAZ': { name: 'Kazakhstan', code2: 'kz', emoji: '🇰🇿' },
  'BLR': { name: 'Belarus', code2: 'by', emoji: '🇧🇾' },
  'EST': { name: 'Estonia', code2: 'ee', emoji: '🇪🇪' },
  'LAT': { name: 'Latvia', code2: 'lv', emoji: '🇱🇻' },
  'LTU': { name: 'Lithuania', code2: 'lt', emoji: '🇱🇹' },
  'LUX': { name: 'Luxembourg', code2: 'lu', emoji: '🇱🇺' },
  'MNE': { name: 'Montenegro', code2: 'me', emoji: '🇲🇪' },
  'MKD': { name: 'North Macedonia', code2: 'mk', emoji: '🇲🇰' },
  'BIH': { name: 'Bosnia & Herzegovina', code2: 'ba', emoji: '🇧🇦' },
  'MLT': { name: 'Malta', code2: 'mt', emoji: '🇲🇹' },
  'AND': { name: 'Andorra', code2: 'ad', emoji: '🇦🇩' },
  'SMR': { name: 'San Marino', code2: 'sm', emoji: '🇸🇲' },
  'LIE': { name: 'Liechtenstein', code2: 'li', emoji: '🇱🇮' },
  'GIB': { name: 'Gibraltar', code2: 'gi', emoji: '🇬🇮' },
  'FRO': { name: 'Faroes', code2: 'fo', emoji: '🇫🇴' },
  'XKX': { name: 'Kosovo', code2: 'xk', emoji: '🇽🇰' },
};

export const FORMATIONS: Record<string, { GK:number; DEF:number; MID:number; ATT:number }> = {
  '4-3-3': { GK:1, DEF:4, MID:3, ATT:3 },
  '4-4-2': { GK:1, DEF:4, MID:4, ATT:2 },
  '4-2-3-1': { GK:1, DEF:4, MID:5, ATT:1 },
  '3-5-2': { GK:1, DEF:3, MID:5, ATT:2 },
  '5-3-2': { GK:1, DEF:5, MID:3, ATT:2 },
};

export const BADGES = ['⚽','🦅','🦁','🐺','⚓','⚔️','🌟','🛡️','🏰','🐉','🔥','⚡','🌹','👑','🐂','🦈'];
export const COLORS = [
  { primary: '#dc2626', secondary: '#0f172a' },
  { primary: '#2563eb', secondary: '#f8fafc' },
  { primary: '#16a34a', secondary: '#0f172a' },
  { primary: '#facc15', secondary: '#1e293b' },
  { primary: '#7c3aed', secondary: '#f8fafc' },
  { primary: '#ea580c', secondary: '#1e293b' },
  { primary: '#0891b2', secondary: '#f8fafc' },
  { primary: '#db2777', secondary: '#0f172a' },
];

export const CLUB_PRESETS_D1 = [
  { name: 'Manchester Rovers', short: 'MRV', badge: '🦁', city: 'Manchester' },
  { name: 'Real Madrigal', short: 'MAD', badge: '👑', city: 'Madrid' },
  { name: 'Bayern Stern', short: 'BST', badge: '⭐', city: 'Munich' },
  { name: 'Paris Lumière', short: 'PAR', badge: '🗼', city: 'Paris' },
  { name: 'Milano Nero', short: 'MIL', badge: '🛡️', city: 'Milan' },
  { name: 'Barcelona Azul', short: 'BAR', badge: '🔵', city: 'Barcelona' },
  { name: 'Liverpool Tides', short: 'LIV', badge: '⚓', city: 'Liverpool' },
  { name: 'Juventus Bianco', short: 'JUV', badge: '⚪', city: 'Turin' },
  { name: 'Amsterdam Ajax', short: 'AJX', badge: '⚔️', city: 'Amsterdam' },
  { name: 'Lisboa Águia', short: 'LIS', badge: '🦅', city: 'Lisbon' },
  { name: 'Porto Drago', short: 'POR', badge: '🐉', city: 'Porto' },
  { name: 'Roma Lupi', short: 'ROM', badge: '🐺', city: 'Rome' },
  { name: 'Sevilla Rosa', short: 'SEV', badge: '🌹', city: 'Seville' },
  { name: 'Dortmund Storm', short: 'DOR', badge: '⚡', city: 'Dortmund' },
  { name: 'Napoli Vesuvio', short: 'NAP', badge: '🔥', city: 'Naples' },
  { name: 'Glasgow Bulls', short: 'GLA', badge: '🐂', city: 'Glasgow' },
  { name: 'London Lions', short: 'LON', badge: '🦁', city: 'London' },
  { name: 'Madrid Atlético', short: 'ATM', badge: '🛡️', city: 'Madrid' },
  { name: 'Marseille Voile', short: 'MAR', badge: '⛵', city: 'Marseille' },
  { name: 'Valencia Bats', short: 'VAL', badge: '🦇', city: 'Valencia' },
];

export const CLUB_PRESETS_D2 = [
  'Leeds United','Norwich Canaries','Sunderland Black Cats','Sheffield Steel','Bristol City',
  'Espanyol Pericos','Real Betis','Celta Vigo','Mallorca Isla','Cádiz Submarino',
  'Schalke 04','Hamburger SV','Werder Bremen','Hertha Berlin','Köln Goats',
  'Lyon Olympique','Toulouse Pastel','Nice Aigles','Rennes Roussillon','Lille Mastiff',
].map((name, i) => ({ name, short: name.slice(0,3).toUpperCase(), badge: BADGES[i % BADGES.length], city: name.split(' ')[0] }));
